<?php

namespace CIS\Bundle\CompentencyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompentencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompentencyRepository extends EntityRepository
{
}
