CIS\Bundle\CompentencyBundle\Entity\Compentency:
    type: entity
    table: Compentency
    repositoryClass: CIS\Bundle\CompentencyBundle\Entity\CompentencyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        soverignId:
            type: string
            length: 255
        name:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        description:
            type: string
            length: 1000
    manyToOne:
        entity:
            targetEntity: Entity
            inversedBy: compentencies
    manyToMany:
        courses:
            targetEntity: Course
            joinTable:
                name: compentency_course
                joinColumns:
                    compentency_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    course_id:
                        referencedColumnName: id
        externalCompentencies:
            targetEntity: Compentency
            joinTable:
                name: capella_compentency_external_compentency
                joinColumns:
                    capella_compentency_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    external_compentency_id:
                        referencedColumnName: id
        tags:
            targetEntity: Tag
            joinTable:
                name: compentency_tag
                joinColumns:
                    compentency_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
