parameters:
#    cis_website.example.class: CIS\Bundle\WebsiteBundle\Example

services:
#    cis_website.example:
#        class: %cis_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
