<?php

namespace CIS\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CapabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapabilityRepository extends EntityRepository
{
}
